#!/usr/bin/env bash
# post_100_famous_authors.sh
# Envía 100 POSTs a http://localhost:2007/authors usando 100 autores famosos y descripciones en español.

PORT=2007
BASE_URL="http://localhost:${PORT}/authors"
COD_USER_CREATED="1756412232"

names=(
  "William Shakespeare"
  "Miguel de Cervantes"
  "León Tolstói"
  "Charles Dickens"
  "Jane Austen"
  "Mark Twain"
  "Víctor Hugo"
  "Fiódor Dostoievski"
  "Homero"
  "Dante Alighieri"
  "Johann Wolfgang von Goethe"
  "Franz Kafka"
  "James Joyce"
  "Gabriel García Márquez"
  "Virginia Woolf"
  "George Orwell"
  "F. Scott Fitzgerald"
  "Ernest Hemingway"
  "Herman Melville"
  "J.R.R. Tolkien"
  "C.S. Lewis"
  "George Eliot"
  "Marcel Proust"
  "Gustave Flaubert"
  "Émile Zola"
  "Albert Camus"
  "Jorge Luis Borges"
  "Salman Rushdie"
  "J.K. Rowling"
  "Stephen King"
  "Agatha Christie"
  "Arthur Conan Doyle"
  "Chinua Achebe"
  "Haruki Murakami"
  "Paulo Coelho"
  "Khaled Hosseini"
  "Cormac McCarthy"
  "Toni Morrison"
  "John Steinbeck"
  "Mario Vargas Llosa"
  "Pablo Neruda"
  "Rumi"
  "Aleksandr Pushkin"
  "Murasaki Shikibu"
  "Geoffrey Chaucer"
  "Miguel de Unamuno"
  "Nikolái Gógol"
  "Antón Chéjov"
  "Rabindranath Tagore"
  "George R.R. Martin"
  "Isabel Allende"
  "Yukio Mishima"
  "Aldous Huxley"
  "Hermann Hesse"
  "John Milton"
  "Ken Follett"
  "J.D. Salinger"
  "Roald Dahl"
  "Dan Brown"
  "William Faulkner"
  "José Saramago"
  "Bram Stoker"
  "Mary Shelley"
  "Charlotte Brontë"
  "Emily Brontë"
  "Zadie Smith"
  "Ian McEwan"
  "Julian Barnes"
  "Margaret Atwood"
  "Doris Lessing"
  "Barbara Kingsolver"
  "Elizabeth Gilbert"
  "Neil Gaiman"
  "Terry Pratchett"
  "Philip K. Dick"
  "Ursula K. Le Guin"
  "Isaac Asimov"
  "Arthur C. Clarke"
  "H.G. Wells"
  "George Bernard Shaw"
  "Tennessee Williams"
  "Henrik Ibsen"
  "Sófocles"
  "Eurípides"
  "Esquilo"
  "Lao-Tsé"
  "Confucio"
  "Nicolás Maquiavelo"
  "Tomás Moro"
  "Stendhal"
  "Charles Baudelaire"
  "William Wordsworth"
  "Samuel Taylor Coleridge"
  "Alexandre Dumas"
  "Honoré de Balzac"
  "Friedrich Schiller"
  "John Keats"
  "Percy Bysshe Shelley"
  "Walt Whitman"
  "T.S. Eliot"
)

descriptions=(
  "Dramaturgo y poeta inglés, autor de Romeo y Julieta y Hamlet."
  "Novelista español, autor de Don Quijote de la Mancha."
  "Novelista ruso, autor de Guerra y Paz."
  "Novelista inglés, autor de Oliver Twist y Historia de dos ciudades."
  "Novelista inglesa, autora de Orgullo y Prejuicio y Sensatez y Sentimiento."
  "Autor estadounidense, conocido por Las aventuras de Tom Sawyer y Huckleberry Finn."
  "Escritor francés, autor de Los Miserables y Nuestra Señora de París."
  "Novelista ruso, autor de Crimen y Castigo y El Idiota."
  "Poeta épico griego, atribuido a la Ilíada y la Odisea."
  "Poeta italiano, autor de La Divina Comedia."
  "Escritor alemán, autor de Fausto."
  "Escritor checo de habla alemana, autor de La metamorfosis."
  "Novelista irlandés, autor de Ulises."
  "Novelista colombiano, autor de Cien años de soledad."
  "Novelista inglesa, autora de Mrs Dalloway y Al faro."
  "Escritor inglés, autor de 1984 y Rebelión en la granja."
  "Escritor estadounidense, autor de El gran Gatsby."
  "Novelista estadounidense, autor de El viejo y el mar."
  "Novelista estadounidense, autor de Moby Dick."
  "Escritor británico, autor de El Señor de los Anillos y El Hobbit."
  "Escritor británico, autor de Las crónicas de Narnia."
  "Seudónimo de Mary Ann Evans, autora de Middlemarch."
  "Novelista francés, autor de En busca del tiempo perdido."
  "Novelista francés, autor de Madame Bovary."
  "Novelista francés, figura del naturalismo, autor de Germinal."
  "Filósofo y escritor francés, autor de El extranjero."
  "Escritor argentino, pionero del realismo mágico, autor de Ficciones."
  "Escritor británico de origen indio, autor de Hijos de la medianoche."
  "Escritora británica, autora de la saga Harry Potter."
  "Autor estadounidense, maestro del terror, autor de It y Carrie."
  "Escritora británica, reina del misterio, autora de Asesinato en el Orient Express."
  "Escritor británico, creador del detective Sherlock Holmes."
  "Novelista nigeriano, autor de Todo se desmorona."
  "Escritor japonés contemporáneo, autor de Kafka en la orilla."
  "Escritor brasileño, autor de El alquimista."
  "Escritor afgano-estadounidense, autor de Cometas en el cielo."
  "Novelista estadounidense, autor de La carretera."
  "Novelista estadounidense, autora de Beloved."
  "Escritor estadounidense, autor de Las uvas de la ira."
  "Escritor peruano, premio Nobel, autor de La ciudad y los perros."
  "Poeta chileno, premio Nobel, autor de Veinte poemas de amor."
  "Poeta persa del siglo XIII y místico sufí."
  "Poeta ruso, autor de Eugenio Oneguin."
  "Escritora japonesa del siglo XI, autora de La historia de Genji."
  "Poeta inglés, autor de Los cuentos de Canterbury."
  "Escritor y filósofo español, autor del Tratado del sentido de la vida."
  "Escritor ruso, autor de Almas muertas."
  "Dramaturgo y cuentista ruso, autor de La gaviota."
  "Poeta indio, premio Nobel, autor de Gitanjali."
  "Escritor estadounidense, autor de Canción de hielo y fuego."
  "Escritora chilena, autora de La casa de los espíritus."
  "Novelista y dramaturgo japonés, autor de El pabellón de oro."
  "Escritor inglés, autor de Un mundo feliz."
  "Escritor germano-suizo, autor de Siddhartha."
  "Poeta inglés, autor de El paraíso perdido."
  "Escritor galés, autor de Los Pilares de la Tierra."
  "Escritor estadounidense, autor de El guardián entre el centeno."
  "Escritor británico, autor de Charlie y la fábrica de chocolate."
  "Escritor estadounidense, autor de El código Da Vinci."
  "Escritor estadounidense, autor de El ruido y la furia."
  "Escritor portugués, premio Nobel, autor de Ensayo sobre la ceguera."
  "Escritor irlandés, autor de Drácula."
  "Escritora inglesa, autora de Frankenstein."
  "Novelista inglesa, autora de Jane Eyre."
  "Novelista inglesa, autora de Cumbres Borrascosas."
  "Novelista británica contemporánea, autora de Dientes blancos."
  "Novelista inglesa, autora de Expiación."
  "Escritor británico, autor de El sentido del final."
  "Escritora canadiense, autora de El cuento de la criada."
  "Escritora británica, premio Nobel."
  "Novelista estadounidense, autora de El veneno de los árboles."
  "Escritora estadounidense, autora de Come, reza, ama."
  "Escritor británico, autor de American Gods."
  "Escritor inglés, autor de la serie Mundodisco."
  "Autor estadounidense, autor de ¿Sueñan los androides con ovejas eléctricas?"
  "Escritora estadounidense, autora de La mano izquierda de la oscuridad."
  "Escritor ruso-estadounidense, autor de la serie Fundación."
  "Escritor británico de ciencia ficción, autor de 2001: Una odisea del espacio."
  "Escritor inglés, autor de La guerra de los mundos."
  "Dramaturgo irlandés, autor de Pigmalión."
  "Dramaturgo estadounidense, autor de Un tranvía llamado Deseo."
  "Dramaturgo noruego, autor de Casa de muñecas."
  "Dramaturgo griego antiguo, autor de Edipo Rey."
  "Dramaturgo griego antiguo, autor de Medea."
  "Dramaturgo griego antiguo, autor de Los persas."
  "Filósofo chino antiguo, autor del Tao Te Ching."
  "Filósofo y maestro chino, autor de los Analectas."
  "Filósofo político italiano, autor de El Príncipe."
  "Humanista inglés, autor de Utopía."
  "Escritor francés, autor de Rojo y negro."
  "Poeta francés, autor de Las flores del mal."
  "Poeta romántico inglés."
  "Poeta inglés, autor de El viejo marinero."
  "Escritor francés, autor de El conde de Montecristo."
  "Novelista francés, autor de La Comedia Humana."
  "Poeta alemán, autor de la Oda a la Alegría."
  "Poeta romántico inglés."
  "Poeta romántico inglés, autor de Ozymandias."
  "Poeta estadounidense, autor de Hojas de hierba."
  "Poeta y dramaturgo anglo-estadounidense, autor de La tierra baldía."
)

for i in "${!names[@]}"; do
  idx=$(printf "%03d" $((i+1)))
  cod="AUTH${idx}"
  name="${names[$i]}"
  description="${descriptions[$i]}"

  curl  -X POST "${BASE_URL}" \
    -H "Content-Type: application/json" \
    -d "{\"name\":\"${name}\",\"description\":\"${description}\",\"cod\":\"${cod}\",\"codUserCreated\":\"${COD_USER_CREATED}\"}"

  echo
done
